import img1 from "../assets/science.jpg";

export const questions = [
  {
    title: "What is Data Analysis?",
    desc: "lorem ipsum",
    img: img1,
    reacted: true,
    count: 30,
    authorId: "Darshana Thamara",
  },
  {
    title: "What is AI?",
    desc: "lorem ipsumsdds",
    img: img1,
    reacted: false,
    count: 50,
    authorId: "Darshana Thamara",
  },
  {
    title: "Rate immersive technology? ",
    desc: "lorem ipsumsddsdssdsd",
    img: img1,
    reacted: true,
    count: 80,
    authorId: "Darshana Thamara",
  },
  {
    title: "Who is the fastest man in the world?",
    desc: "lorem ipsumdsdsdssdsd",
    img: img1,
    reacted: false,
    count: 30,
    authorId: "Darshana Thamara",
  },
  {
    title: "What is AI?",
    desc: "lorem ipsumsdds",
    img: img1,
    reacted: false,
    count: 50,
    authorId: "Darshana Thamara",
  },
  {
    title: "Rate immersive technology? ",
    desc: "lorem ipsumsddsdssdsd",
    img: img1,
    reacted: true,
    count: 80,
    authorId: "Darshana Thamara",
  },
  {
    title: "Who is the fastest man in the world?",
    desc: "lorem ipsumdsdsdssdsd",
    img: img1,
    reacted: false,
    count: 30,
    authorId: "Darshana Thamara",
  },
];
