import NavBar from "@/components/navbar/NavBar";
import "./globals.css";

// const poppins = Poppins({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/path/to/fonts.css" />
      </head>
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
